var classes = [
    {
        "name": "Anax\\Route\\RouteMatcher",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "checkPartAsArgument",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "checkPartMatchingType",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "typeConvertArgument",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "matchPart",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "matchRequestMethod",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "match",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 5,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 32,
        "ccn": 27,
        "ccnMethodMax": 13,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 224,
        "vocabulary": 51,
        "volume": 1270.62,
        "difficulty": 23.08,
        "effort": 29322.08,
        "level": 0.04,
        "bugs": 0.42,
        "time": 1629,
        "intelligentContent": 55.06,
        "number_operators": 74,
        "number_operands": 150,
        "number_operators_unique": 12,
        "number_operands_unique": 39,
        "cloc": 71,
        "loc": 185,
        "lloc": 114,
        "mi": 70.72,
        "mIwoC": 29.76,
        "commentWeight": 40.95,
        "kanDefect": 1.37,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 3.33,
        "relativeSystemComplexity": 28.33,
        "totalStructuralComplexity": 150,
        "totalDataComplexity": 20,
        "totalSystemComplexity": 170,
        "package": "Anax\\Route\\",
        "pageRank": 0.11,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Anax\\Route\\Route",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "set",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "match",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setMatchedPath",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMatchedPath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setName",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setArguments",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getInfo",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPath",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAbsolutePath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRequestMethod",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHandlerType",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 12,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 3,
        "wmc": 19,
        "ccn": 13,
        "ccnMethodMax": 5,
        "externals": [
            "Anax\\Route\\RouteMatcher",
            "Psr\\Container\\ContainerInterface",
            "Anax\\Route\\RouteHandler",
            "Anax\\Route\\Exception\\ConfigurationException",
            "Psr\\Container\\ContainerInterface",
            "Anax\\Route\\RouteHandler"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 182,
        "vocabulary": 34,
        "volume": 925.92,
        "difficulty": 16.33,
        "effort": 15123.33,
        "level": 0.06,
        "bugs": 0.31,
        "time": 840,
        "intelligentContent": 56.69,
        "number_operators": 56,
        "number_operands": 126,
        "number_operators_unique": 7,
        "number_operands_unique": 27,
        "cloc": 97,
        "loc": 205,
        "lloc": 108,
        "mi": 76.88,
        "mIwoC": 33.12,
        "commentWeight": 43.76,
        "kanDefect": 0.71,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 2.51,
        "relativeSystemComplexity": 27.51,
        "totalStructuralComplexity": 300,
        "totalDataComplexity": 30.17,
        "totalSystemComplexity": 330.17,
        "package": "Anax\\Route\\",
        "pageRank": 0.12,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "Anax\\Route\\Router",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "setMode",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addRoutes",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createMountPath",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addRoute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addInternalRoute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handleInternal",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addController",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "any",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "always",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "all",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "post",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "put",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "patch",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "options",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLastRoute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMatchedPath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getErrorMessage",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAll",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getInternal",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 23,
        "nbMethods": 19,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 18,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 1,
        "wmc": 52,
        "ccn": 34,
        "ccnMethodMax": 15,
        "externals": [
            "Anax\\Commons\\ContainerInjectableInterface",
            "Anax\\Route\\Exception\\ConfigurationException",
            "Anax\\Route\\Route",
            "Anax\\Route\\Route",
            "Anax\\Route\\Exception\\NotFoundException"
        ],
        "parents": [],
        "implements": [
            "Anax\\Commons\\ContainerInjectableInterface"
        ],
        "lcom": 1,
        "length": 310,
        "vocabulary": 40,
        "volume": 1649.8,
        "difficulty": 30.25,
        "effort": 49906.38,
        "level": 0.03,
        "bugs": 0.55,
        "time": 2773,
        "intelligentContent": 54.54,
        "number_operators": 68,
        "number_operands": 242,
        "number_operators_unique": 8,
        "number_operands_unique": 32,
        "cloc": 230,
        "loc": 403,
        "lloc": 173,
        "mi": 70.12,
        "mIwoC": 24.08,
        "commentWeight": 46.04,
        "kanDefect": 1.61,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 1.39,
        "relativeSystemComplexity": 145.39,
        "totalStructuralComplexity": 3312,
        "totalDataComplexity": 32.08,
        "totalSystemComplexity": 3344.08,
        "package": "Anax\\Route\\",
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Anax\\Route\\RouteHandler",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHandlerType",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isInvocableClass",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handleAsInvocableClass",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isControllerAction",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handleAsControllerAction",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handleAsCallable",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handleUsingDi",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 6,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 80,
        "ccn": 73,
        "ccnMethodMax": 15,
        "externals": [
            "Psr\\Container\\ContainerInterface",
            "Anax\\Route\\Exception\\ConfigurationException",
            "Psr\\Container\\ContainerInterface",
            "ReflectionClass",
            "class",
            "ReflectionClass",
            "Anax\\Route\\Exception\\ConfigurationException",
            "ReflectionMethod",
            "ReflectionMethod",
            "Anax\\Route\\Exception\\NotFoundException",
            "Anax\\Route\\Exception\\NotFoundException",
            "ReflectionMethod",
            "Anax\\Route\\Exception\\NotFoundException",
            "ReflectionMethod",
            "Anax\\Route\\Exception\\NotFoundException",
            "class",
            "ReflectionClass",
            "Anax\\Route\\Exception\\ConfigurationException",
            "ReflectionMethod",
            "ReflectionMethod",
            "Anax\\Route\\Exception\\NotFoundException",
            "Anax\\Route\\Exception\\NotFoundException",
            "Anax\\Route\\Exception\\NotFoundException",
            "ReflectionMethod",
            "action",
            "ReflectionMethod",
            "ReflectionFunction",
            "Psr\\Container\\ContainerInterface",
            "Anax\\Route\\Exception\\ConfigurationException",
            "Anax\\Route\\Exception\\ConfigurationException"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 494,
        "vocabulary": 66,
        "volume": 2985.93,
        "difficulty": 24.55,
        "effort": 73309.75,
        "level": 0.04,
        "bugs": 1,
        "time": 4073,
        "intelligentContent": 121.62,
        "number_operators": 138,
        "number_operands": 356,
        "number_operators_unique": 8,
        "number_operands_unique": 58,
        "cloc": 93,
        "loc": 300,
        "lloc": 207,
        "mi": 53.3,
        "mIwoC": 15.33,
        "commentWeight": 37.98,
        "kanDefect": 3.17,
        "relativeStructuralComplexity": 441,
        "relativeDataComplexity": 1.1,
        "relativeSystemComplexity": 442.1,
        "totalStructuralComplexity": 3528,
        "totalDataComplexity": 8.82,
        "totalSystemComplexity": 3536.82,
        "package": "Anax\\Route\\",
        "pageRank": 0.17,
        "afferentCoupling": 1,
        "efferentCoupling": 8,
        "instability": 0.89,
        "violations": {}
    },
    {
        "name": "Anax\\Route\\Exception\\ForbiddenException",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 8,
        "lloc": 4,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Anax\\Route\\Exception\\",
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Anax\\Route\\Exception\\InternalErrorException",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 8,
        "lloc": 4,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Anax\\Route\\Exception\\",
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Anax\\Route\\Exception\\NotFoundException",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 4,
        "loc": 8,
        "lloc": 4,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Anax\\Route\\Exception\\",
        "pageRank": 0.2,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "Anax\\Route\\Exception\\ConfigurationException",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 3,
        "loc": 7,
        "lloc": 4,
        "mi": 213.45,
        "mIwoC": 171,
        "commentWeight": 42.45,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Anax\\Route\\Exception\\",
        "pageRank": 0.22,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    }
]